namespace Audyt_innowacyjności.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class newquestion : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Surveys", "Branza", c => c.String());
            AddColumn("dbo.Surveys", "IloscPracownikow", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "WprowadzoneInnowacje", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "NowePomysły", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "ZyskiNoweWyroby", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "ZyskiInnowacjeInne", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "DlugoscCykli", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "WydatkiInnowacyjnosc", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "SredniaIloscPomyslow", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "SklonnoscDoRyzyka", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "PoszerzenieOferty", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "UlatwienieDzialanProdukcyjnych", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "PoprawaJakosciUslug", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "WzrostPrestizu", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "NoweKontakty", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "ZmniejszenieKosztow", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "OdpowiedziDoKlientow", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "PomiarStopniaInnowacyjnosciKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "PomiarStopniaSwiadczonychUslug", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "PomiarStopniaSwiadczonychUslugKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "RynekUsług", c => c.String());
            AddColumn("dbo.Surveys", "CenyWStosunkuDoKonkurencji", c => c.String());
            AddColumn("dbo.Surveys", "KonkurentISubstytuty", c => c.String());
            AddColumn("dbo.Surveys", "RozniceProduktow", c => c.String());
            AddColumn("dbo.Surveys", "RozbudowaOferty", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LepszaPromocja", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "ModernizacjaZaplecza", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "NoweOprogramowanie", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "InneDzialania", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "InneDzialaniaKomentarz", c => c.String());
            DropColumn("dbo.Surveys", "IloscZmian");
            DropColumn("dbo.Surveys", "IloscUmowOPrace");
            DropColumn("dbo.Surveys", "IloscUmowCywilnoPrawnych");
            DropColumn("dbo.Surveys", "IloscPracownikowSezonowych");
            DropColumn("dbo.Surveys", "ZmianyWStrukturze");
            DropColumn("dbo.Surveys", "ModelBiznesowy");
            DropColumn("dbo.Surveys", "ObszaryDzialanosci");
            DropColumn("dbo.Surveys", "KomunikacjaWewnetrzna");
            DropColumn("dbo.Surveys", "ZarzadzanieRelacjami");
            DropColumn("dbo.Surveys", "RelacjeIOB");
            DropColumn("dbo.Surveys", "RelacjeZInstytucjami");
            DropColumn("dbo.Surveys", "PracownicyKomentarz");
            DropColumn("dbo.Surveys", "KonkurenciKomentarz");
            DropColumn("dbo.Surveys", "KlienciKomentarz");
            DropColumn("dbo.Surveys", "FirmyDoradczeKomentarz");
            DropColumn("dbo.Surveys", "UczelnieKomentarz");
            DropColumn("dbo.Surveys", "PlacowkiKomentarz");
            DropColumn("dbo.Surveys", "Badania");
            DropColumn("dbo.Surveys", "BadaniaKomentarz");
            DropColumn("dbo.Surveys", "CzasTrwaniaBadan");
            DropColumn("dbo.Surveys", "BadaniaNaRozwoj");
            DropColumn("dbo.Surveys", "BadaniaNaRozwojKomentarz");
            DropColumn("dbo.Surveys", "InneNazwa");
            DropColumn("dbo.Surveys", "NowechProdukty");
            DropColumn("dbo.Surveys", "LiczbaNowychProduktow");
            DropColumn("dbo.Surveys", "WielkoscSprzedazy");
            DropColumn("dbo.Surveys", "ProcentowaWielkoscSprzedazy");
            DropColumn("dbo.Surveys", "SprzedazInne");
            DropColumn("dbo.Surveys", "WartoscSprzedazy");
            DropColumn("dbo.Surveys", "Zyski");
            DropColumn("dbo.Surveys", "WartoscZyskow");
            DropColumn("dbo.Surveys", "NowePomysly");
            DropColumn("dbo.Surveys", "LiczbaNowychPomyslow");
            DropColumn("dbo.Surveys", "NieudaneProjekty");
            DropColumn("dbo.Surveys", "LiczbaNieudanychProjektow");
            DropColumn("dbo.Surveys", "CzyObliczanyCzas");
            DropColumn("dbo.Surveys", "Czas");
            DropColumn("dbo.Surveys", "ZgloszeniaPatentowe");
            DropColumn("dbo.Surveys", "LiczbaZgloszenPatentowych");
            DropColumn("dbo.Surveys", "PlanowaneProjekty");
            DropColumn("dbo.Surveys", "LiczbaPlanowanychProjektow");
            DropColumn("dbo.Surveys", "OdrzuconeProjekty");
            DropColumn("dbo.Surveys", "LiczbaOdrzuconychProjektow");
            DropColumn("dbo.Surveys", "PracownicyZNowymiPomyslami");
            DropColumn("dbo.Surveys", "LiczbaPracownikowZNowymiPomyslami");
            DropColumn("dbo.Surveys", "NowePomyslySrednia");
            DropColumn("dbo.Surveys", "LiczbaNowychPomyslowSrednia");
            DropColumn("dbo.Surveys", "CzasNaInnowacyjnosc");
            DropColumn("dbo.Surveys", "IleCzasuNaInnowacyjnosc");
            DropColumn("dbo.Surveys", "InneWskazniki");
            DropColumn("dbo.Surveys", "WartoscInnych");
            DropColumn("dbo.Surveys", "Wartosc1");
            DropColumn("dbo.Surveys", "Wartosc2");
            DropColumn("dbo.Surveys", "Wartosc3");
            DropColumn("dbo.Surveys", "Wartosc4");
            DropColumn("dbo.Surveys", "Wartosc5");
            DropColumn("dbo.Surveys", "Wartosc6");
            DropColumn("dbo.Surveys", "Wartosc7");
            DropColumn("dbo.Surveys", "Wartosc8");
            DropColumn("dbo.Surveys", "Wartosc9");
            DropColumn("dbo.Surveys", "Wartosc10");
            DropColumn("dbo.Surveys", "OdbiorcaUslug");
            DropColumn("dbo.Surveys", "RelacjeFirmy");
            DropColumn("dbo.Surveys", "UzytkownikKoncowy");
            DropColumn("dbo.Surveys", "PotrzebyProduktow");
            DropColumn("dbo.Surveys", "PowodyWyboruProduktow");
            DropColumn("dbo.Surveys", "RynekUslug");
            DropColumn("dbo.Surveys", "PerspektywaRozwoju");
            DropColumn("dbo.Surveys", "IstnienieStrategi");
            DropColumn("dbo.Surveys", "Strategia");
            DropColumn("dbo.Surveys", "Ceny");
            DropColumn("dbo.Surveys", "UstalanieCen");
            DropColumn("dbo.Surveys", "Marza");
            DropColumn("dbo.Surveys", "ZyskownoscBranzy");
            DropColumn("dbo.Surveys", "ZyskownoscFirmy");
            DropColumn("dbo.Surveys", "Konkurent");
            DropColumn("dbo.Surveys", "OferantSybtytuty");
            DropColumn("dbo.Surveys", "PotrzebySybtytutow");
            DropColumn("dbo.Surveys", "RoznicaProduktow");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Surveys", "RoznicaProduktow", c => c.String());
            AddColumn("dbo.Surveys", "PotrzebySybtytutow", c => c.String());
            AddColumn("dbo.Surveys", "OferantSybtytuty", c => c.String());
            AddColumn("dbo.Surveys", "Konkurent", c => c.String());
            AddColumn("dbo.Surveys", "ZyskownoscFirmy", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "ZyskownoscBranzy", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Marza", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "UstalanieCen", c => c.String());
            AddColumn("dbo.Surveys", "Ceny", c => c.String());
            AddColumn("dbo.Surveys", "Strategia", c => c.String());
            AddColumn("dbo.Surveys", "IstnienieStrategi", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "PerspektywaRozwoju", c => c.String());
            AddColumn("dbo.Surveys", "RynekUslug", c => c.String());
            AddColumn("dbo.Surveys", "PowodyWyboruProduktow", c => c.String());
            AddColumn("dbo.Surveys", "PotrzebyProduktow", c => c.String());
            AddColumn("dbo.Surveys", "UzytkownikKoncowy", c => c.String());
            AddColumn("dbo.Surveys", "RelacjeFirmy", c => c.String());
            AddColumn("dbo.Surveys", "OdbiorcaUslug", c => c.String());
            AddColumn("dbo.Surveys", "Wartosc10", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc9", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc8", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc7", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc6", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc5", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc4", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc3", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc2", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc1", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "WartoscInnych", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "InneWskazniki", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "IleCzasuNaInnowacyjnosc", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "CzasNaInnowacyjnosc", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaNowychPomyslowSrednia", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "NowePomyslySrednia", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaPracownikowZNowymiPomyslami", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "PracownicyZNowymiPomyslami", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaOdrzuconychProjektow", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "OdrzuconeProjekty", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaPlanowanychProjektow", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "PlanowaneProjekty", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaZgloszenPatentowych", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "ZgloszeniaPatentowe", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "Czas", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "CzyObliczanyCzas", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaNieudanychProjektow", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "NieudaneProjekty", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaNowychPomyslow", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "NowePomysly", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "WartoscZyskow", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Zyski", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "WartoscSprzedazy", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "SprzedazInne", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "ProcentowaWielkoscSprzedazy", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "WielkoscSprzedazy", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaNowychProduktow", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "NowechProdukty", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "InneNazwa", c => c.String());
            AddColumn("dbo.Surveys", "BadaniaNaRozwojKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "BadaniaNaRozwoj", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "CzasTrwaniaBadan", c => c.String());
            AddColumn("dbo.Surveys", "BadaniaKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "Badania", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "PlacowkiKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "UczelnieKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "FirmyDoradczeKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "KlienciKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "KonkurenciKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "PracownicyKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "RelacjeZInstytucjami", c => c.String());
            AddColumn("dbo.Surveys", "RelacjeIOB", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "ZarzadzanieRelacjami", c => c.String());
            AddColumn("dbo.Surveys", "KomunikacjaWewnetrzna", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "ObszaryDzialanosci", c => c.String());
            AddColumn("dbo.Surveys", "ModelBiznesowy", c => c.String());
            AddColumn("dbo.Surveys", "ZmianyWStrukturze", c => c.String());
            AddColumn("dbo.Surveys", "IloscPracownikowSezonowych", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "IloscUmowCywilnoPrawnych", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "IloscUmowOPrace", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "IloscZmian", c => c.Int(nullable: false));
            DropColumn("dbo.Surveys", "InneDzialaniaKomentarz");
            DropColumn("dbo.Surveys", "InneDzialania");
            DropColumn("dbo.Surveys", "NoweOprogramowanie");
            DropColumn("dbo.Surveys", "ModernizacjaZaplecza");
            DropColumn("dbo.Surveys", "LepszaPromocja");
            DropColumn("dbo.Surveys", "RozbudowaOferty");
            DropColumn("dbo.Surveys", "RozniceProduktow");
            DropColumn("dbo.Surveys", "KonkurentISubstytuty");
            DropColumn("dbo.Surveys", "CenyWStosunkuDoKonkurencji");
            DropColumn("dbo.Surveys", "RynekUsług");
            DropColumn("dbo.Surveys", "PomiarStopniaSwiadczonychUslugKomentarz");
            DropColumn("dbo.Surveys", "PomiarStopniaSwiadczonychUslug");
            DropColumn("dbo.Surveys", "PomiarStopniaInnowacyjnosciKomentarz");
            DropColumn("dbo.Surveys", "OdpowiedziDoKlientow");
            DropColumn("dbo.Surveys", "ZmniejszenieKosztow");
            DropColumn("dbo.Surveys", "NoweKontakty");
            DropColumn("dbo.Surveys", "WzrostPrestizu");
            DropColumn("dbo.Surveys", "PoprawaJakosciUslug");
            DropColumn("dbo.Surveys", "UlatwienieDzialanProdukcyjnych");
            DropColumn("dbo.Surveys", "PoszerzenieOferty");
            DropColumn("dbo.Surveys", "SklonnoscDoRyzyka");
            DropColumn("dbo.Surveys", "SredniaIloscPomyslow");
            DropColumn("dbo.Surveys", "WydatkiInnowacyjnosc");
            DropColumn("dbo.Surveys", "DlugoscCykli");
            DropColumn("dbo.Surveys", "ZyskiInnowacjeInne");
            DropColumn("dbo.Surveys", "ZyskiNoweWyroby");
            DropColumn("dbo.Surveys", "NowePomysły");
            DropColumn("dbo.Surveys", "WprowadzoneInnowacje");
            DropColumn("dbo.Surveys", "IloscPracownikow");
            DropColumn("dbo.Surveys", "Branza");
        }
    }
}
