// <auto-generated />
namespace Audyt_innowacyjności.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class commentenumproperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(commentenumproperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201807312155091_comment enum properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
