namespace Audyt_innowacyjności.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Allproperties : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Surveys", "WiekPrzedsiebiorstwa", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "IloscUmowOPrace", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "IloscUmowCywilnoPrawnych", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "IloscPracownikowSezonowych", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "ZmianyWStrukturze", c => c.String());
            AddColumn("dbo.Surveys", "PoziomWyksztalcenia", c => c.String());
            AddColumn("dbo.Surveys", "StazPracy", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "WiekZatrudnienia", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Obroty", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Zysk", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "AktywaNiematerialne", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "AktywaMaterialne", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "AktywaPrawne", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "ModelBiznesowy", c => c.String());
            AddColumn("dbo.Surveys", "ZasiegDzialanosci", c => c.String());
            AddColumn("dbo.Surveys", "ObszaryDzialanosci", c => c.String());
            AddColumn("dbo.Surveys", "SzczebleHierarchiPionowej", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "KoordynacjaPracy", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "KoordynacjaPracyKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "PracaZespolowa", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "KomunikacjaWewnetrzna", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "WsparcieInnowacji", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "Innowacyjnosc", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "ZarzadzanieRelacjami", c => c.String());
            AddColumn("dbo.Surveys", "ZwiazkiFirmy", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "StosunkiZAgencjami", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "RelacjeIOB", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "StosunkiZInstytucjami", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "RelacjeZInstytucjami", c => c.String());
            AddColumn("dbo.Surveys", "ProcesoweLiczba", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "ProcesoweKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "ProduktoweLiczba", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "ProduktoweKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "OrgnizacyjneLiczba", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "OrgnizacyjneKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "MarketingoweLiczba", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "MarketingoweKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "BarieryWewnetrzne", c => c.String());
            AddColumn("dbo.Surveys", "BarieryZewnetrzne", c => c.String());
            AddColumn("dbo.Surveys", "MocneStrony", c => c.String());
            AddColumn("dbo.Surveys", "SlabeStrony", c => c.String());
            AddColumn("dbo.Surveys", "Szanse", c => c.String());
            AddColumn("dbo.Surveys", "Zagrozenia", c => c.String());
            AddColumn("dbo.Surveys", "Pracownicy", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "PracownicyKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "Konkurencji", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "KonkurencjiKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "Klienci", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "KlienciKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "FirmyDoradcze", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "FirmyDoradczeKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "Uczelnie", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "UczelnieKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "Placowki", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "PlacowkiKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "Inne", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "InneKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "PraceBadawczeKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "KoloLubOrganizacja", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "KoloLubOrganizacjaKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "CertyfikatJakosci", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "CertyfikatJakosciKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "Badania", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "BadaniaKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "CzasTrwaniaBadan", c => c.String());
            AddColumn("dbo.Surveys", "BadaniaNaRozwoj", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "BadaniaNaRozwojKomentarz", c => c.String());
            AddColumn("dbo.Surveys", "InneNazwa", c => c.String());
            AddColumn("dbo.Surveys", "PomiarStopniaInnowacyjnosci", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "NowechProdukty", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaNowychProduktow", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "WielkoscSprzedazy", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "ProcentowaWielkoscSprzedazy", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "SprzedazInne", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "WartoscSprzedazy", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Zyski", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "WartoscZyskow", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "NowePomysly", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaNowychPomyslow", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "NieudaneProjekty", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaNieudanychProjektow", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "CzyObliczanyCzas", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "Czas", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "ZgloszeniaPatentowe", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaZgloszenPatentowych", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "PlanowaneProjekty", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaPlanowanychProjektow", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "OdrzuconeProjekty", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaOdrzuconychProjektow", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "PracownicyZNowymiPomyslami", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaPracownikowZNowymiPomyslami", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "NowePomyslySrednia", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "LiczbaNowychPomyslowSrednia", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "CzasNaInnowacyjnosc", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "IleCzasuNaInnowacyjnosc", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "InneWskazniki", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "WartoscInnych", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "WyrobFirmy1", c => c.String());
            AddColumn("dbo.Surveys", "WyrobFirmy2", c => c.String());
            AddColumn("dbo.Surveys", "WyrobFirmy3", c => c.String());
            AddColumn("dbo.Surveys", "WyrobFirmy4", c => c.String());
            AddColumn("dbo.Surveys", "WyrobFirmy5", c => c.String());
            AddColumn("dbo.Surveys", "WyrobFirmy6", c => c.String());
            AddColumn("dbo.Surveys", "WyrobFirmy7", c => c.String());
            AddColumn("dbo.Surveys", "WyrobFirmy8", c => c.String());
            AddColumn("dbo.Surveys", "WyrobFirmy9", c => c.String());
            AddColumn("dbo.Surveys", "WyrobFirmy10", c => c.String());
            AddColumn("dbo.Surveys", "Wartosc1", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc2", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc3", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc4", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc5", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc6", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc7", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc8", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc9", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "Wartosc10", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "OdbiorcaUslug", c => c.String());
            AddColumn("dbo.Surveys", "RelacjeFirmy", c => c.String());
            AddColumn("dbo.Surveys", "UzytkownikKoncowy", c => c.String());
            AddColumn("dbo.Surveys", "PotrzebyProduktow", c => c.String());
            AddColumn("dbo.Surveys", "PowodyWyboruProduktow", c => c.String());
            AddColumn("dbo.Surveys", "RynekUslug", c => c.String());
            AddColumn("dbo.Surveys", "PerspektywaRozwoju", c => c.String());
            AddColumn("dbo.Surveys", "StrategiaRozwoju", c => c.String());
            AddColumn("dbo.Surveys", "IstnienieStrategi", c => c.Boolean(nullable: false));
            AddColumn("dbo.Surveys", "Strategia", c => c.String());
            AddColumn("dbo.Surveys", "Ceny", c => c.String());
            AddColumn("dbo.Surveys", "UstalanieCen", c => c.String());
            AddColumn("dbo.Surveys", "Marza", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "ZyskownoscBranzy", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "ZyskownoscFirmy", c => c.Int(nullable: false));
            AddColumn("dbo.Surveys", "PrzewagaKonkurencyjna", c => c.String());
            AddColumn("dbo.Surveys", "Konkurent", c => c.String());
            AddColumn("dbo.Surveys", "OferantSybtytuty", c => c.String());
            AddColumn("dbo.Surveys", "PotrzebySybtytutow", c => c.String());
            AddColumn("dbo.Surveys", "RoznicaProduktow", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.Surveys", "RoznicaProduktow");
            DropColumn("dbo.Surveys", "PotrzebySybtytutow");
            DropColumn("dbo.Surveys", "OferantSybtytuty");
            DropColumn("dbo.Surveys", "Konkurent");
            DropColumn("dbo.Surveys", "PrzewagaKonkurencyjna");
            DropColumn("dbo.Surveys", "ZyskownoscFirmy");
            DropColumn("dbo.Surveys", "ZyskownoscBranzy");
            DropColumn("dbo.Surveys", "Marza");
            DropColumn("dbo.Surveys", "UstalanieCen");
            DropColumn("dbo.Surveys", "Ceny");
            DropColumn("dbo.Surveys", "Strategia");
            DropColumn("dbo.Surveys", "IstnienieStrategi");
            DropColumn("dbo.Surveys", "StrategiaRozwoju");
            DropColumn("dbo.Surveys", "PerspektywaRozwoju");
            DropColumn("dbo.Surveys", "RynekUslug");
            DropColumn("dbo.Surveys", "PowodyWyboruProduktow");
            DropColumn("dbo.Surveys", "PotrzebyProduktow");
            DropColumn("dbo.Surveys", "UzytkownikKoncowy");
            DropColumn("dbo.Surveys", "RelacjeFirmy");
            DropColumn("dbo.Surveys", "OdbiorcaUslug");
            DropColumn("dbo.Surveys", "Wartosc10");
            DropColumn("dbo.Surveys", "Wartosc9");
            DropColumn("dbo.Surveys", "Wartosc8");
            DropColumn("dbo.Surveys", "Wartosc7");
            DropColumn("dbo.Surveys", "Wartosc6");
            DropColumn("dbo.Surveys", "Wartosc5");
            DropColumn("dbo.Surveys", "Wartosc4");
            DropColumn("dbo.Surveys", "Wartosc3");
            DropColumn("dbo.Surveys", "Wartosc2");
            DropColumn("dbo.Surveys", "Wartosc1");
            DropColumn("dbo.Surveys", "WyrobFirmy10");
            DropColumn("dbo.Surveys", "WyrobFirmy9");
            DropColumn("dbo.Surveys", "WyrobFirmy8");
            DropColumn("dbo.Surveys", "WyrobFirmy7");
            DropColumn("dbo.Surveys", "WyrobFirmy6");
            DropColumn("dbo.Surveys", "WyrobFirmy5");
            DropColumn("dbo.Surveys", "WyrobFirmy4");
            DropColumn("dbo.Surveys", "WyrobFirmy3");
            DropColumn("dbo.Surveys", "WyrobFirmy2");
            DropColumn("dbo.Surveys", "WyrobFirmy1");
            DropColumn("dbo.Surveys", "WartoscInnych");
            DropColumn("dbo.Surveys", "InneWskazniki");
            DropColumn("dbo.Surveys", "IleCzasuNaInnowacyjnosc");
            DropColumn("dbo.Surveys", "CzasNaInnowacyjnosc");
            DropColumn("dbo.Surveys", "LiczbaNowychPomyslowSrednia");
            DropColumn("dbo.Surveys", "NowePomyslySrednia");
            DropColumn("dbo.Surveys", "LiczbaPracownikowZNowymiPomyslami");
            DropColumn("dbo.Surveys", "PracownicyZNowymiPomyslami");
            DropColumn("dbo.Surveys", "LiczbaOdrzuconychProjektow");
            DropColumn("dbo.Surveys", "OdrzuconeProjekty");
            DropColumn("dbo.Surveys", "LiczbaPlanowanychProjektow");
            DropColumn("dbo.Surveys", "PlanowaneProjekty");
            DropColumn("dbo.Surveys", "LiczbaZgloszenPatentowych");
            DropColumn("dbo.Surveys", "ZgloszeniaPatentowe");
            DropColumn("dbo.Surveys", "Czas");
            DropColumn("dbo.Surveys", "CzyObliczanyCzas");
            DropColumn("dbo.Surveys", "LiczbaNieudanychProjektow");
            DropColumn("dbo.Surveys", "NieudaneProjekty");
            DropColumn("dbo.Surveys", "LiczbaNowychPomyslow");
            DropColumn("dbo.Surveys", "NowePomysly");
            DropColumn("dbo.Surveys", "WartoscZyskow");
            DropColumn("dbo.Surveys", "Zyski");
            DropColumn("dbo.Surveys", "WartoscSprzedazy");
            DropColumn("dbo.Surveys", "SprzedazInne");
            DropColumn("dbo.Surveys", "ProcentowaWielkoscSprzedazy");
            DropColumn("dbo.Surveys", "WielkoscSprzedazy");
            DropColumn("dbo.Surveys", "LiczbaNowychProduktow");
            DropColumn("dbo.Surveys", "NowechProdukty");
            DropColumn("dbo.Surveys", "PomiarStopniaInnowacyjnosci");
            DropColumn("dbo.Surveys", "InneNazwa");
            DropColumn("dbo.Surveys", "BadaniaNaRozwojKomentarz");
            DropColumn("dbo.Surveys", "BadaniaNaRozwoj");
            DropColumn("dbo.Surveys", "CzasTrwaniaBadan");
            DropColumn("dbo.Surveys", "BadaniaKomentarz");
            DropColumn("dbo.Surveys", "Badania");
            DropColumn("dbo.Surveys", "CertyfikatJakosciKomentarz");
            DropColumn("dbo.Surveys", "CertyfikatJakosci");
            DropColumn("dbo.Surveys", "KoloLubOrganizacjaKomentarz");
            DropColumn("dbo.Surveys", "KoloLubOrganizacja");
            DropColumn("dbo.Surveys", "PraceBadawczeKomentarz");
            DropColumn("dbo.Surveys", "InneKomentarz");
            DropColumn("dbo.Surveys", "Inne");
            DropColumn("dbo.Surveys", "PlacowkiKomentarz");
            DropColumn("dbo.Surveys", "Placowki");
            DropColumn("dbo.Surveys", "UczelnieKomentarz");
            DropColumn("dbo.Surveys", "Uczelnie");
            DropColumn("dbo.Surveys", "FirmyDoradczeKomentarz");
            DropColumn("dbo.Surveys", "FirmyDoradcze");
            DropColumn("dbo.Surveys", "KlienciKomentarz");
            DropColumn("dbo.Surveys", "Klienci");
            DropColumn("dbo.Surveys", "KonkurencjiKomentarz");
            DropColumn("dbo.Surveys", "Konkurencji");
            DropColumn("dbo.Surveys", "PracownicyKomentarz");
            DropColumn("dbo.Surveys", "Pracownicy");
            DropColumn("dbo.Surveys", "Zagrozenia");
            DropColumn("dbo.Surveys", "Szanse");
            DropColumn("dbo.Surveys", "SlabeStrony");
            DropColumn("dbo.Surveys", "MocneStrony");
            DropColumn("dbo.Surveys", "BarieryZewnetrzne");
            DropColumn("dbo.Surveys", "BarieryWewnetrzne");
            DropColumn("dbo.Surveys", "MarketingoweKomentarz");
            DropColumn("dbo.Surveys", "MarketingoweLiczba");
            DropColumn("dbo.Surveys", "OrgnizacyjneKomentarz");
            DropColumn("dbo.Surveys", "OrgnizacyjneLiczba");
            DropColumn("dbo.Surveys", "ProduktoweKomentarz");
            DropColumn("dbo.Surveys", "ProduktoweLiczba");
            DropColumn("dbo.Surveys", "ProcesoweKomentarz");
            DropColumn("dbo.Surveys", "ProcesoweLiczba");
            DropColumn("dbo.Surveys", "RelacjeZInstytucjami");
            DropColumn("dbo.Surveys", "StosunkiZInstytucjami");
            DropColumn("dbo.Surveys", "RelacjeIOB");
            DropColumn("dbo.Surveys", "StosunkiZAgencjami");
            DropColumn("dbo.Surveys", "ZwiazkiFirmy");
            DropColumn("dbo.Surveys", "ZarzadzanieRelacjami");
            DropColumn("dbo.Surveys", "Innowacyjnosc");
            DropColumn("dbo.Surveys", "WsparcieInnowacji");
            DropColumn("dbo.Surveys", "KomunikacjaWewnetrzna");
            DropColumn("dbo.Surveys", "PracaZespolowa");
            DropColumn("dbo.Surveys", "KoordynacjaPracyKomentarz");
            DropColumn("dbo.Surveys", "KoordynacjaPracy");
            DropColumn("dbo.Surveys", "SzczebleHierarchiPionowej");
            DropColumn("dbo.Surveys", "ObszaryDzialanosci");
            DropColumn("dbo.Surveys", "ZasiegDzialanosci");
            DropColumn("dbo.Surveys", "ModelBiznesowy");
            DropColumn("dbo.Surveys", "AktywaPrawne");
            DropColumn("dbo.Surveys", "AktywaMaterialne");
            DropColumn("dbo.Surveys", "AktywaNiematerialne");
            DropColumn("dbo.Surveys", "Zysk");
            DropColumn("dbo.Surveys", "Obroty");
            DropColumn("dbo.Surveys", "WiekZatrudnienia");
            DropColumn("dbo.Surveys", "StazPracy");
            DropColumn("dbo.Surveys", "PoziomWyksztalcenia");
            DropColumn("dbo.Surveys", "ZmianyWStrukturze");
            DropColumn("dbo.Surveys", "IloscPracownikowSezonowych");
            DropColumn("dbo.Surveys", "IloscUmowCywilnoPrawnych");
            DropColumn("dbo.Surveys", "IloscUmowOPrace");
            DropColumn("dbo.Surveys", "WiekPrzedsiebiorstwa");
        }
    }
}
